<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<script>
  function liang() {
    //1. 用new Promise將整個代碼包裹起來
    //3. 將整個new Promise對象拋出
    return new Promise(
      function (door,err) {
        var bang="Liang's stick";
        console.log(`Liang take ${bang} start run`);
        setTimeout(() => {//異步
          if (Math.random()<0.6) {
            console.log("Liang end");
            console.log("Liang open the door");
            //2. 在異部函數最後一句話執行完，開門通知下一個人可以開始執行
            door(bang);//return bang
          }else{
            console.log(`Liang failed`);
            err('Liang cry');
          }
        }, 6000);
      }
    )

  }
  function ran(bang) {
    // 1. 用new Promise()包裹所有代碼
    //3. 將Promise return出來
    return new Promise(
      function (door,err) {
        console.log(`Ran take ${bang} start run`);
          setTimeout(() => {
            if (Math.random()<0.6) {
              console.log("Ran end");
              console.log("Ran open the door");
              //2. 當前任務結束自動調用開關door()開門通知下一個函數可以開始進行
              door(bang);
          }else{
              console.log(`Ran failed`);
              err('Ran cry');
            }

          }
          , 6000);

      }
    )
  }
  function dong(bang) {
    return new Promise(
      function (door,err) {
        var bang=`Dong's stick`
        console.log(`Dong take ${bang} start run`);
        setTimeout(() => {
          if(Math.random()<0.6){
            console.log("Dong end");
            console.log("Dong open the door");
            door(bang);
         }else{
            console.log('Dong failed');
            err('Dong cry');
          }
        }, 6000);
      }
    )
  }
//es7的async和 await僅僅簡化的是promise函數調用的部分
(async function () {
  try {
    var bang=await liang();//await 代替.then()
    bang=await ran(bang);
    await dong(bang);
    console.log('比賽結束')
  } catch (err) {//代替.catch()
    console.log(err);
    console.log("集體退賽!!");
  }
})()
</script>
</body>
</html>
